name: Continuous Integration

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: qr-code-component


jobs:
  build:
    environment: stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Echo Taco
        run: echo ${{ secrets.TACO }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest
